CREATE DATABASE DataQuanNet
GO
USE DataQuanNet
GO
CREATE TABLE DangNhap
(	
	TaiKhoan NVARCHAR(20) NOT NULL PRIMARY KEY,
	MatKhau NVARCHAR(20) NULL
)
GO
CREATE FUNCTION dbo.AUTO_IDMay()
RETURNS NVARCHAR(20)
AS
BEGIN
	DECLARE @ID NVARCHAR(20)
	IF (SELECT COUNT(MaMay) FROM May) = 0
		SET @ID = N'0'
	ELSE
		SELECT @ID = MAX(RIGHT(MaMay, 4)) FROM May
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN N'MAY000' + CONVERT(NVARCHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN N'MAY00' + CONVERT(NVARCHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 99 THEN N'MAY0' + CONVERT(NVARCHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 999 THEN N'MAY' + CONVERT(NVARCHAR, CONVERT(INT, @ID) + 1)
		END
	RETURN @ID
END
GO
CREATE TABLE May
(
     MaMay NVARCHAR(20) CONSTRAINT IDMay DEFAULT dbo.AUTO_IDMay() PRIMARY KEY,
	 TenMay NVARCHAR(100) NULL,
	 TrangThai BIT DEFAULT 0
)
GO
CREATE TABLE KhachHang
(
     SDT NVARCHAR(20) PRIMARY KEY,
	 TenKH NVARCHAR(100)  NULL,
	 DiaChi NVARCHAR(200) NULL
)
GO
CREATE FUNCTION dbo.AUTO_IDDichVu()
RETURNS NVARCHAR(20)
AS
BEGIN
	DECLARE @ID NVARCHAR(20)
	IF (SELECT COUNT(MaDV) FROM DichVu) = 0
		SET @ID = N'0'
	ELSE
		SELECT @ID = MAX(RIGHT(MaDV, 4)) FROM DichVu
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN N'DV000' + CONVERT(NVARCHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN N'DV00' + CONVERT(NVARCHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 99 THEN N'DV0' + CONVERT(NVARCHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 999 THEN N'DV' + CONVERT(NVARCHAR, CONVERT(INT, @ID) + 1)
		END
	RETURN @ID
END
GO
CREATE TABLE DichVu
(
     MaDV NVARCHAR(20)  CONSTRAINT IDDV DEFAULT dbo.AUTO_IDDichVu() PRIMARY KEY,
	 TenDV NVARCHAR(100) NULL,
	 DonViTinh NVARCHAR(50) NULL,
	 DonGia INT DEFAULT 0
)
GO
CREATE FUNCTION dbo.AUTO_IDHD()
RETURNS NVARCHAR(20)
AS
BEGIN
	DECLARE @ID NVARCHAR(20)
	IF (SELECT COUNT(MaHD) FROM HoaDon) = 0
		SET @ID = N'0'
	ELSE
		SELECT @ID = MAX(RIGHT(MaHD, 4)) FROM HoaDon
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN N'HD000' + CONVERT(NVARCHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN N'HD00' + CONVERT(NVARCHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 99 THEN N'HD0' + CONVERT(NVARCHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 999 THEN N'HD' + CONVERT(NVARCHAR, CONVERT(INT, @ID) + 1)
		END
	RETURN @ID
END
GO
CREATE TABLE HoaDon
(
     MaHD NVARCHAR(20)  CONSTRAINT IDHD DEFAULT dbo.AUTO_IDHD() PRIMARY KEY,
	 SDTKH NVARCHAR(20) NULL,
	 MaMay NVARCHAR(20) NULL,
	 ThoiGianBatDau DATETIME DEFAULT GETDATE(),
	 ThoiGianKetThuc DATETIME DEFAULT GETDATE(),
	 TongTien INT DEFAULT 0,
	 TrangThai BIT DEFAULT 0
	 FOREIGN KEY (SDTKH) REFERENCES dbo.KhachHang(SDT),
	 FOREIGN KEY (MaMay) REFERENCES dbo.May(MaMay)
)
GO
CREATE FUNCTION dbo.AUTO_IDCTHD()
RETURNS NVARCHAR(20)
AS
BEGIN
	DECLARE @ID NVARCHAR(20)
	IF (SELECT COUNT(MaCT) FROM ChiTietHoaDon) = 0
		SET @ID = N'0'
	ELSE
		SELECT @ID = MAX(RIGHT(MaCT, 4)) FROM ChiTietHoaDon
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN N'CT000' + CONVERT(NVARCHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN N'CT00' + CONVERT(NVARCHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN N'CT0' + CONVERT(NVARCHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN N'CT' + CONVERT(NVARCHAR, CONVERT(INT, @ID) + 1)
		END
	RETURN @ID
END
GO
CREATE TABLE ChiTietHoaDon
(
     MaCT NVARCHAR(20) CONSTRAINT IDCTHD DEFAULT dbo.AUTO_IDCTHD() PRIMARY KEY,
	 MaHD NVARCHAR(20) NULL,
	 MaDV NVARCHAR(20) NULL,
	 DonGia INT  NULL,
	 SoLuong FLOAT NULL
	 FOREIGN KEY (MaHD) REFERENCES dbo.HoaDon(MaHD),
	 FOREIGN KEY (MaDV) REFERENCES dbo.DichVu(MaDV)
)
GO
INSERT INTO DangNhap VALUES(N'admin',N'1234')
GO
INSERT INTO DichVu(TenDV,DonViTinh,DonGia) VALUES(N'NET',N'Giờ',20000)
GO
INSERT INTO DichVu(TenDV,DonViTinh,DonGia) VALUES(N'Mỳ tôm trứng',N'Tô',20000)
GO
INSERT INTO DichVu(TenDV,DonViTinh,DonGia) VALUES(N'Sting dâu',N'Chai',15000)
GO
INSERT INTO DichVu(TenDV,DonViTinh,DonGia) VALUES(N'Sting vàng',N'Chai',12000)
GO
INSERT INTO DichVu(TenDV,DonViTinh,DonGia) VALUES(N'Thuốc ngựa',N'Gói',35000)
GO
INSERT INTO KhachHang(SDT,TenKH,DiaChi) VALUES(N'0000000000',N'Khách vãn lai',N'Trống')
GO
INSERT INTO May(TenMay) VALUES(N'Máy 1')
GO
INSERT INTO May(TenMay) VALUES(N'Máy 2')
GO
INSERT INTO May(TenMay) VALUES(N'Máy 3')
GO
INSERT INTO May(TenMay) VALUES(N'Máy 4')
GO
INSERT INTO May(TenMay) VALUES(N'Máy 5')
GO
INSERT INTO May(TenMay) VALUES(N'Máy 6')
GO
INSERT INTO May(TenMay) VALUES(N'Máy 7')
GO
INSERT INTO May(TenMay) VALUES(N'Máy 8')
GO
INSERT INTO May(TenMay) VALUES(N'Máy 9')
GO
INSERT INTO May(TenMay) VALUES(N'Máy 10')
GO
INSERT INTO May(TenMay) VALUES(N'Máy 11')
GO
INSERT INTO May(TenMay) VALUES(N'Máy 12')
GO
INSERT INTO May(TenMay) VALUES(N'Máy 13')
GO
INSERT INTO May(TenMay) VALUES(N'Máy 14')
GO
INSERT INTO May(TenMay) VALUES(N'Máy 15')
GO
INSERT INTO May(TenMay) VALUES(N'Máy 16')
GO
